package main

import (
	"github.com/the-jira-cloud-platform-rest-api/mcp-server/config"
	"github.com/the-jira-cloud-platform-rest-api/mcp-server/models"
	tools_screen_tab_fields "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/screen_tab_fields"
	tools_projects "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/projects"
	tools_filters "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/filters"
	tools_project_roles "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_roles"
	tools_workflow_transition_rules "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/workflow_transition_rules"
	tools_issue_fields "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_fields"
	tools_screens "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/screens"
	tools_issue_custom_field_options_apps "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_custom_field_options_apps"
	tools_jql "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/jql"
	tools_project_features "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_features"
	tools_issue_type_properties "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_type_properties"
	tools_application_roles "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/application_roles"
	tools_issue_custom_field_contexts "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_custom_field_contexts"
	tools_user_search "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/user_search"
	tools_workflow_scheme_drafts "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/workflow_scheme_drafts"
	tools_issue_navigator_settings "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_navigator_settings"
	tools_issue_security_schemes "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_security_schemes"
	tools_project_avatars "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_avatars"
	tools_issue_attachments "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_attachments"
	tools_jira_settings "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/jira_settings"
	tools_users "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/users"
	tools_issue_field_configurations "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_field_configurations"
	tools_project_properties "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_properties"
	tools_myself "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/myself"
	tools_issue_search "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_search"
	tools_app_migration "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/app_migration"
	tools_issue_type_schemes "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_type_schemes"
	tools_issue_watchers "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_watchers"
	tools_project_permission_schemes "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_permission_schemes"
	tools_groups "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/groups"
	tools_issue_types "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_types"
	tools_issue_worklogs "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_worklogs"
	tools_time_tracking "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/time_tracking"
	tools_avatars "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/avatars"
	tools_workflows "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/workflows"
	tools_project_types "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_types"
	tools_issue_priorities "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_priorities"
	tools_dashboards "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/dashboards"
	tools_issue_custom_field_options "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_custom_field_options"
	tools_screen_tabs "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/screen_tabs"
	tools_issue_notification_schemes "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_notification_schemes"
	tools_permission_schemes "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/permission_schemes"
	tools_workflow_status_categories "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/workflow_status_categories"
	tools_project_versions "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_versions"
	tools_issue_links "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_links"
	tools_jql_functions_apps "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/jql_functions_apps"
	tools_issue_security_level "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_security_level"
	tools_user_properties "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/user_properties"
	tools_issues "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issues"
	tools_issue_comments "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_comments"
	tools_workflow_schemes "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/workflow_schemes"
	tools_issue_comment_properties "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_comment_properties"
	tools_issue_remote_links "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_remote_links"
	tools_issue_type_screen_schemes "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_type_screen_schemes"
	tools_webhooks "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/webhooks"
	tools_ui_modifications_apps "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/ui_modifications_apps"
	tools_dynamic_modules "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/dynamic_modules"
	tools_issue_resolutions "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_resolutions"
	tools_project_key_and_name_validation "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_key_and_name_validation"
	tools_project_components "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_components"
	tools_project_role_actors "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_role_actors"
	tools_jira_expressions "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/jira_expressions"
	tools_permissions "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/permissions"
	tools_app_properties "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/app_properties"
	tools_issue_custom_field_configuration_apps "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_custom_field_configuration_apps"
	tools_workflow_statuses "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/workflow_statuses"
	tools_announcement_banner "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/announcement_banner"
	tools_issue_properties "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_properties"
	tools_project_categories "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_categories"
	tools_status "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/status"
	tools_labels "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/labels"
	tools_tasks "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/tasks"
	tools_workflow_scheme_project_associations "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/workflow_scheme_project_associations"
	tools_server_info "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/server_info"
	tools_issue_link_types "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_link_types"
	tools_license_metrics "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/license_metrics"
	tools_project_email "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/project_email"
	tools_issue_custom_field_values_apps "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_custom_field_values_apps"
	tools_filter_sharing "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/filter_sharing"
	tools_group_and_user_picker "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/group_and_user_picker"
	tools_issue_worklog_properties "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_worklog_properties"
	tools_audit_records "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/audit_records"
	tools_workflow_transition_properties "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/workflow_transition_properties"
	tools_issue_votes "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/issue_votes"
	tools_screen_schemes "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/screen_schemes"
	tools_instance_information "github.com/the-jira-cloud-platform-rest-api/mcp-server/tools/instance_information"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_screen_tab_fields.CreateMovescreentabfieldTool(cfg),
		tools_projects.CreateGetallprojectsTool(cfg),
		tools_projects.CreateCreateprojectTool(cfg),
		tools_filters.CreateResetcolumnsTool(cfg),
		tools_filters.CreateGetcolumnsTool(cfg),
		tools_filters.CreateSetcolumnsTool(cfg),
		tools_project_roles.CreateGetprojectrolesTool(cfg),
		tools_workflow_transition_rules.CreateGetworkflowtransitionruleconfigurationsTool(cfg),
		tools_workflow_transition_rules.CreateUpdateworkflowtransitionruleconfigurationsTool(cfg),
		tools_issue_fields.CreateDeletecustomfieldTool(cfg),
		tools_screens.CreateGetavailablescreenfieldsTool(cfg),
		tools_issue_custom_field_options_apps.CreateReplaceissuefieldoptionTool(cfg),
		tools_filters.CreateGetfilterspaginatedTool(cfg),
		tools_issue_custom_field_options_apps.CreateGetallissuefieldoptionsTool(cfg),
		tools_issue_custom_field_options_apps.CreateCreateissuefieldoptionTool(cfg),
		tools_jql.CreateMigratequeriesTool(cfg),
		tools_project_features.CreateGetfeaturesforprojectTool(cfg),
		tools_issue_type_properties.CreateSetissuetypepropertyTool(cfg),
		tools_issue_type_properties.CreateDeleteissuetypepropertyTool(cfg),
		tools_issue_type_properties.CreateGetissuetypepropertyTool(cfg),
		tools_issue_custom_field_options_apps.CreateGetselectableissuefieldoptionsTool(cfg),
		tools_application_roles.CreateGetapplicationroleTool(cfg),
		tools_issue_custom_field_contexts.CreateAddissuetypestocontextTool(cfg),
		tools_user_search.CreateFindusersbyqueryTool(cfg),
		tools_workflow_scheme_drafts.CreateDeletedraftworkflowmappingTool(cfg),
		tools_workflow_scheme_drafts.CreateGetdraftworkflowTool(cfg),
		tools_workflow_scheme_drafts.CreateUpdatedraftworkflowmappingTool(cfg),
		tools_issue_navigator_settings.CreateSetissuenavigatordefaultcolumnsTool(cfg),
		tools_issue_navigator_settings.CreateGetissuenavigatordefaultcolumnsTool(cfg),
		tools_issue_security_schemes.CreateDeletesecurityschemeTool(cfg),
		tools_jql.CreateGetfieldautocompleteforquerystringTool(cfg),
		tools_project_avatars.CreateGetallprojectavatarsTool(cfg),
		tools_issue_attachments.CreateGetattachmentthumbnailTool(cfg),
		tools_project_roles.CreateGetallprojectrolesTool(cfg),
		tools_project_roles.CreateCreateprojectroleTool(cfg),
		tools_jira_settings.CreateGetadvancedsettingsTool(cfg),
		tools_filters.CreateGetfavouritefiltersTool(cfg),
		tools_jira_settings.CreateGetapplicationpropertyTool(cfg),
		tools_users.CreateGetallusersdefaultTool(cfg),
		tools_issue_field_configurations.CreateRemoveissuetypesfromglobalfieldconfigurationschemeTool(cfg),
		tools_project_properties.CreateGetprojectpropertykeysTool(cfg),
		tools_myself.CreateGetcurrentuserTool(cfg),
		tools_issue_attachments.CreateExpandattachmentformachinesTool(cfg),
		tools_issue_search.CreateSearchforissuesusingjqlTool(cfg),
		tools_issue_search.CreateSearchforissuesusingjqlpostTool(cfg),
		tools_issue_security_schemes.CreateAddsecuritylevelTool(cfg),
		tools_app_migration.CreateMigrationresource_workflowrulesearch_postTool(cfg),
		tools_screens.CreateGetscreensTool(cfg),
		tools_screens.CreateCreatescreenTool(cfg),
		tools_issue_field_configurations.CreateDeletefieldconfigurationTool(cfg),
		tools_issue_field_configurations.CreateUpdatefieldconfigurationTool(cfg),
		tools_issue_type_properties.CreateGetissuetypepropertykeysTool(cfg),
		tools_users.CreateGetuseremailTool(cfg),
		tools_projects.CreateGetnotificationschemeforprojectTool(cfg),
		tools_issue_type_schemes.CreateDeleteissuetypeschemeTool(cfg),
		tools_issue_type_schemes.CreateUpdateissuetypeschemeTool(cfg),
		tools_issue_watchers.CreateRemovewatcherTool(cfg),
		tools_issue_watchers.CreateGetissuewatchersTool(cfg),
		tools_issue_watchers.CreateAddwatcherTool(cfg),
		tools_project_permission_schemes.CreateGetassignedpermissionschemeTool(cfg),
		tools_project_permission_schemes.CreateAssignpermissionschemeTool(cfg),
		tools_groups.CreateFindgroupsTool(cfg),
		tools_issue_type_schemes.CreateGetissuetypeschemesmappingTool(cfg),
		tools_user_search.CreateFindassignableusersTool(cfg),
		tools_issue_types.CreateCreateissuetypeavatarTool(cfg),
		tools_issue_worklogs.CreateGetidsofworklogsmodifiedsinceTool(cfg),
		tools_time_tracking.CreateGetavailabletimetrackingimplementationsTool(cfg),
		tools_issue_attachments.CreateGetattachmentcontentTool(cfg),
		tools_avatars.CreateGetavatarimagebyownerTool(cfg),
		tools_workflows.CreateDeleteinactiveworkflowTool(cfg),
		tools_project_types.CreateGetallaccessibleprojecttypesTool(cfg),
		tools_issue_priorities.CreateGetprioritiesTool(cfg),
		tools_issue_priorities.CreateCreatepriorityTool(cfg),
		tools_dashboards.CreateCopydashboardTool(cfg),
		tools_myself.CreateSetpreferenceTool(cfg),
		tools_myself.CreateRemovepreferenceTool(cfg),
		tools_myself.CreateGetpreferenceTool(cfg),
		tools_issue_custom_field_options.CreateDeletecustomfieldoptionTool(cfg),
		tools_screen_tabs.CreateDeletescreentabTool(cfg),
		tools_screen_tabs.CreateRenamescreentabTool(cfg),
		tools_filters.CreateDeletefavouriteforfilterTool(cfg),
		tools_filters.CreateSetfavouriteforfilterTool(cfg),
		tools_issue_notification_schemes.CreateDeletenotificationschemeTool(cfg),
		tools_issue_custom_field_contexts.CreateAssignprojectstocustomfieldcontextTool(cfg),
		tools_permission_schemes.CreateDeletepermissionschemeentityTool(cfg),
		tools_permission_schemes.CreateGetpermissionschemegrantTool(cfg),
		tools_project_avatars.CreateUpdateprojectavatarTool(cfg),
		tools_workflow_status_categories.CreateGetstatuscategoryTool(cfg),
		tools_project_versions.CreateMoveversionTool(cfg),
		tools_issue_links.CreateLinkissuesTool(cfg),
		tools_jql_functions_apps.CreateGetprecomputationsTool(cfg),
		tools_jql_functions_apps.CreateUpdateprecomputationsTool(cfg),
		tools_issue_security_level.CreateGetissuesecuritylevelTool(cfg),
		tools_issue_attachments.CreateRemoveattachmentTool(cfg),
		tools_issue_attachments.CreateGetattachmentTool(cfg),
		tools_user_properties.CreateGetuserpropertykeysTool(cfg),
		tools_issue_type_schemes.CreateAddissuetypestoissuetypeschemeTool(cfg),
		tools_project_types.CreateGetallprojecttypesTool(cfg),
		tools_issues.CreateGetchangelogsTool(cfg),
		tools_issue_comments.CreateGetcommentsbyidsTool(cfg),
		tools_issues.CreateGettransitionsTool(cfg),
		tools_issues.CreateDotransitionTool(cfg),
		tools_user_search.CreateFindusersforpickerTool(cfg),
		tools_workflow_schemes.CreateDeleteworkflowschemeTool(cfg),
		tools_workflow_schemes.CreateGetworkflowschemeTool(cfg),
		tools_workflow_schemes.CreateUpdateworkflowschemeTool(cfg),
		tools_project_versions.CreateGetprojectversionsTool(cfg),
		tools_projects.CreateUpdateprojecttypeTool(cfg),
		tools_issue_comment_properties.CreateDeletecommentpropertyTool(cfg),
		tools_issue_comment_properties.CreateGetcommentpropertyTool(cfg),
		tools_issue_comment_properties.CreateSetcommentpropertyTool(cfg),
		tools_app_migration.CreateAppissuefieldvalueupdateresource_updateissuefields_putTool(cfg),
		tools_issue_types.CreateGetissuetypesforprojectTool(cfg),
		tools_workflow_status_categories.CreateGetstatuscategoriesTool(cfg),
		tools_issue_links.CreateDeleteissuelinkTool(cfg),
		tools_issue_links.CreateGetissuelinkTool(cfg),
		tools_issue_fields.CreateGetcontextsforfielddeprecatedTool(cfg),
		tools_workflow_scheme_drafts.CreateDeleteworkflowschemedraftTool(cfg),
		tools_workflow_scheme_drafts.CreateGetworkflowschemedraftTool(cfg),
		tools_workflow_scheme_drafts.CreateUpdateworkflowschemedraftTool(cfg),
		tools_issue_remote_links.CreateDeleteremoteissuelinkbyglobalidTool(cfg),
		tools_issue_remote_links.CreateGetremoteissuelinksTool(cfg),
		tools_issue_remote_links.CreateCreateorupdateremoteissuelinkTool(cfg),
		tools_issue_security_schemes.CreateSearchsecurityschemesTool(cfg),
		tools_issue_type_screen_schemes.CreateCreateissuetypescreenschemeTool(cfg),
		tools_issue_type_screen_schemes.CreateGetissuetypescreenschemesTool(cfg),
		tools_users.CreateResetusercolumnsTool(cfg),
		tools_users.CreateGetuserdefaultcolumnsTool(cfg),
		tools_users.CreateSetusercolumnsTool(cfg),
		tools_projects.CreateGethierarchyTool(cfg),
		tools_issue_security_level.CreateGetissuesecuritylevelmembersTool(cfg),
		tools_webhooks.CreateDeletewebhookbyidTool(cfg),
		tools_webhooks.CreateGetdynamicwebhooksforappTool(cfg),
		tools_webhooks.CreateRegisterdynamicwebhooksTool(cfg),
		tools_avatars.CreateGetavatarimagebyidTool(cfg),
		tools_ui_modifications_apps.CreateGetuimodificationsTool(cfg),
		tools_ui_modifications_apps.CreateCreateuimodificationTool(cfg),
		tools_dynamic_modules.CreateDynamicmodulesresource_getmodules_getTool(cfg),
		tools_dynamic_modules.CreateDynamicmodulesresource_registermodules_postTool(cfg),
		tools_dynamic_modules.CreateDynamicmodulesresource_removemodules_deleteTool(cfg),
		tools_issue_resolutions.CreateMoveresolutionsTool(cfg),
		tools_project_key_and_name_validation.CreateGetvalidprojectkeyTool(cfg),
		tools_filters.CreateChangefilterownerTool(cfg),
		tools_project_components.CreateGetcomponentTool(cfg),
		tools_project_components.CreateUpdatecomponentTool(cfg),
		tools_project_components.CreateDeletecomponentTool(cfg),
		tools_issue_custom_field_options_apps.CreateDeleteissuefieldoptionTool(cfg),
		tools_issue_custom_field_options_apps.CreateGetissuefieldoptionTool(cfg),
		tools_issue_custom_field_options_apps.CreateUpdateissuefieldoptionTool(cfg),
		tools_project_role_actors.CreateDeleteprojectroleactorsfromroleTool(cfg),
		tools_project_role_actors.CreateGetprojectroleactorsforroleTool(cfg),
		tools_project_role_actors.CreateAddprojectroleactorstoroleTool(cfg),
		tools_issue_type_schemes.CreateGetissuetypeschemeforprojectsTool(cfg),
		tools_issue_type_schemes.CreateAssignissuetypeschemetoprojectTool(cfg),
		tools_avatars.CreateDeleteavatarTool(cfg),
		tools_workflow_schemes.CreateGetallworkflowschemesTool(cfg),
		tools_workflow_schemes.CreateCreateworkflowschemeTool(cfg),
		tools_issue_field_configurations.CreateSetfieldconfigurationschememappingTool(cfg),
		tools_issue_types.CreateGetalternativeissuetypesTool(cfg),
		tools_issue_worklogs.CreateUpdateworklogTool(cfg),
		tools_issue_worklogs.CreateDeleteworklogTool(cfg),
		tools_issue_worklogs.CreateGetworklogTool(cfg),
		tools_issue_notification_schemes.CreateGetnotificationschemetoprojectmappingsTool(cfg),
		tools_workflow_schemes.CreateGetworkflowschemeissuetypeTool(cfg),
		tools_workflow_schemes.CreateSetworkflowschemeissuetypeTool(cfg),
		tools_workflow_schemes.CreateDeleteworkflowschemeissuetypeTool(cfg),
		tools_jira_expressions.CreateEvaluatejiraexpressionTool(cfg),
		tools_issue_security_schemes.CreateAddsecuritylevelmembersTool(cfg),
		tools_dashboards.CreateGetdashboardTool(cfg),
		tools_dashboards.CreateUpdatedashboardTool(cfg),
		tools_dashboards.CreateDeletedashboardTool(cfg),
		tools_issue_type_screen_schemes.CreateGetissuetypescreenschemeprojectassociationsTool(cfg),
		tools_issue_type_screen_schemes.CreateAssignissuetypescreenschemetoprojectTool(cfg),
		tools_issue_custom_field_options.CreateGetcustomfieldoptionTool(cfg),
		tools_issues.CreateGetcreateissuemetaTool(cfg),
		tools_screen_tab_fields.CreateAddscreentabfieldTool(cfg),
		tools_screen_tab_fields.CreateGetallscreentabfieldsTool(cfg),
		tools_permissions.CreateGetpermittedprojectsTool(cfg),
		tools_app_properties.CreateAddonpropertiesresource_deleteaddonproperty_deleteTool(cfg),
		tools_app_properties.CreateAddonpropertiesresource_getaddonproperty_getTool(cfg),
		tools_app_properties.CreateAddonpropertiesresource_putaddonproperty_putTool(cfg),
		tools_issue_custom_field_options_apps.CreateGetvisibleissuefieldoptionsTool(cfg),
		tools_issue_custom_field_configuration_apps.CreateGetcustomfieldconfigurationTool(cfg),
		tools_issue_custom_field_configuration_apps.CreateUpdatecustomfieldconfigurationTool(cfg),
		tools_permission_schemes.CreateGetpermissionschemeTool(cfg),
		tools_permission_schemes.CreateUpdatepermissionschemeTool(cfg),
		tools_permission_schemes.CreateDeletepermissionschemeTool(cfg),
		tools_issue_type_screen_schemes.CreateDeleteissuetypescreenschemeTool(cfg),
		tools_issue_type_screen_schemes.CreateUpdateissuetypescreenschemeTool(cfg),
		tools_issue_type_screen_schemes.CreateUpdatedefaultscreenschemeTool(cfg),
		tools_issue_fields.CreateGetfieldsTool(cfg),
		tools_issue_fields.CreateCreatecustomfieldTool(cfg),
		tools_dashboards.CreateGetallgadgetsTool(cfg),
		tools_dashboards.CreateAddgadgetTool(cfg),
		tools_issue_field_configurations.CreateGetfieldconfigurationschemeprojectmappingTool(cfg),
		tools_issue_field_configurations.CreateAssignfieldconfigurationschemetoprojectTool(cfg),
		tools_issue_fields.CreateGetfieldspaginatedTool(cfg),
		tools_project_versions.CreateGetprojectversionspaginatedTool(cfg),
		tools_projects.CreateRestoreTool(cfg),
		tools_issue_security_schemes.CreateUpdatesecuritylevelTool(cfg),
		tools_issue_security_schemes.CreateRemovelevelTool(cfg),
		tools_dashboards.CreateGetalldashboardsTool(cfg),
		tools_dashboards.CreateCreatedashboardTool(cfg),
		tools_users.CreateGetuseremailbulkTool(cfg),
		tools_permissions.CreateGetallpermissionsTool(cfg),
		tools_projects.CreateSearchprojectsTool(cfg),
		tools_issue_type_screen_schemes.CreateGetprojectsforissuetypescreenschemeTool(cfg),
		tools_project_components.CreateGetprojectcomponentspaginatedTool(cfg),
		tools_projects.CreateGetrecentTool(cfg),
		tools_project_properties.CreateDeleteprojectpropertyTool(cfg),
		tools_project_properties.CreateGetprojectpropertyTool(cfg),
		tools_project_properties.CreateSetprojectpropertyTool(cfg),
		tools_projects.CreateDeleteprojectasynchronouslyTool(cfg),
		tools_myself.CreateDeletelocaleTool(cfg),
		tools_myself.CreateGetlocaleTool(cfg),
		tools_myself.CreateSetlocaleTool(cfg),
		tools_issue_security_schemes.CreateGetsecuritylevelsTool(cfg),
		tools_workflow_transition_rules.CreateDeleteworkflowtransitionruleconfigurationsTool(cfg),
		tools_issues.CreateAssignissueTool(cfg),
		tools_workflow_statuses.CreateGetstatusesTool(cfg),
		tools_issue_fields.CreateTrashcustomfieldTool(cfg),
		tools_time_tracking.CreateGetselectedtimetrackingimplementationTool(cfg),
		tools_time_tracking.CreateSelecttimetrackingimplementationTool(cfg),
		tools_issue_worklogs.CreateGetidsofworklogsdeletedsinceTool(cfg),
		tools_project_types.CreateGetprojecttypebykeyTool(cfg),
		tools_issue_search.CreateGetissuepickerresourceTool(cfg),
		tools_issue_notification_schemes.CreateGetnotificationschemeTool(cfg),
		tools_issue_notification_schemes.CreateUpdatenotificationschemeTool(cfg),
		tools_dashboards.CreateGetdashboarditempropertykeysTool(cfg),
		tools_jql.CreateGetautocompleteTool(cfg),
		tools_jql.CreateGetautocompletepostTool(cfg),
		tools_issue_type_schemes.CreateGetallissuetypeschemesTool(cfg),
		tools_issue_type_schemes.CreateCreateissuetypeschemeTool(cfg),
		tools_issue_search.CreateMatchissuesTool(cfg),
		tools_issue_worklogs.CreateGetissueworklogTool(cfg),
		tools_issue_worklogs.CreateAddworklogTool(cfg),
		tools_issue_attachments.CreateExpandattachmentforhumansTool(cfg),
		tools_project_roles.CreateGetprojectroledetailsTool(cfg),
		tools_workflow_statuses.CreateGetstatusTool(cfg),
		tools_issue_custom_field_options.CreateReordercustomfieldoptionsTool(cfg),
		tools_issue_security_schemes.CreateGetsecuritylevelmembersTool(cfg),
		tools_project_features.CreateTogglefeatureforprojectTool(cfg),
		tools_issue_security_schemes.CreateRemovememberfromsecuritylevelTool(cfg),
		tools_issue_notification_schemes.CreateAddnotificationsTool(cfg),
		tools_project_components.CreateGetcomponentrelatedissuesTool(cfg),
		tools_issue_resolutions.CreateDeleteresolutionTool(cfg),
		tools_issue_resolutions.CreateGetresolutionTool(cfg),
		tools_issue_resolutions.CreateUpdateresolutionTool(cfg),
		tools_issue_custom_field_options.CreateGetoptionsforcontextTool(cfg),
		tools_issue_custom_field_options.CreateCreatecustomfieldoptionTool(cfg),
		tools_issue_custom_field_options.CreateUpdatecustomfieldoptionTool(cfg),
		tools_issue_security_schemes.CreateCreateissuesecurityschemeTool(cfg),
		tools_issue_security_schemes.CreateGetissuesecurityschemesTool(cfg),
		tools_issue_priorities.CreateSearchprioritiesTool(cfg),
		tools_issue_field_configurations.CreateGetallfieldconfigurationschemesTool(cfg),
		tools_issue_field_configurations.CreateCreatefieldconfigurationschemeTool(cfg),
		tools_project_key_and_name_validation.CreateGetvalidprojectnameTool(cfg),
		tools_issue_type_screen_schemes.CreateGetissuetypescreenschememappingsTool(cfg),
		tools_time_tracking.CreateSetsharedtimetrackingconfigurationTool(cfg),
		tools_time_tracking.CreateGetsharedtimetrackingconfigurationTool(cfg),
		tools_issue_custom_field_contexts.CreateRemovecustomfieldcontextfromprojectsTool(cfg),
		tools_announcement_banner.CreateGetbannerTool(cfg),
		tools_announcement_banner.CreateSetbannerTool(cfg),
		tools_issue_priorities.CreateSetdefaultpriorityTool(cfg),
		tools_workflows.CreateGetallworkflowsTool(cfg),
		tools_workflows.CreateCreateworkflowTool(cfg),
		tools_issue_field_configurations.CreateGetfieldconfigurationitemsTool(cfg),
		tools_issue_field_configurations.CreateUpdatefieldconfigurationitemsTool(cfg),
		tools_issue_properties.CreateBulksetissuespropertieslistTool(cfg),
		tools_workflow_scheme_drafts.CreateDeletedraftdefaultworkflowTool(cfg),
		tools_workflow_scheme_drafts.CreateGetdraftdefaultworkflowTool(cfg),
		tools_workflow_scheme_drafts.CreateUpdatedraftdefaultworkflowTool(cfg),
		tools_project_permission_schemes.CreateGetprojectissuesecurityschemeTool(cfg),
		tools_project_versions.CreateDeleteversionTool(cfg),
		tools_project_versions.CreateGetversionTool(cfg),
		tools_project_versions.CreateUpdateversionTool(cfg),
		tools_permissions.CreateGetmypermissionsTool(cfg),
		tools_project_components.CreateGetprojectcomponentsTool(cfg),
		tools_issue_custom_field_contexts.CreateRemoveissuetypesfromcontextTool(cfg),
		tools_permission_schemes.CreateGetallpermissionschemesTool(cfg),
		tools_permission_schemes.CreateCreatepermissionschemeTool(cfg),
		tools_avatars.CreateGetavatarsTool(cfg),
		tools_avatars.CreateStoreavatarTool(cfg),
		tools_project_categories.CreateGetallprojectcategoriesTool(cfg),
		tools_project_categories.CreateCreateprojectcategoryTool(cfg),
		tools_project_roles.CreateGetprojectrolebyidTool(cfg),
		tools_project_roles.CreatePartialupdateprojectroleTool(cfg),
		tools_project_roles.CreateFullyupdateprojectroleTool(cfg),
		tools_project_roles.CreateDeleteprojectroleTool(cfg),
		tools_issue_custom_field_contexts.CreateGetprojectcontextmappingTool(cfg),
		tools_issue_properties.CreateBulksetissuepropertiesbyissueTool(cfg),
		tools_status.CreateDeletestatusesbyidTool(cfg),
		tools_status.CreateGetstatusesbyidTool(cfg),
		tools_status.CreateCreatestatusesTool(cfg),
		tools_status.CreateUpdatestatusesTool(cfg),
		tools_workflow_scheme_drafts.CreatePublishdraftworkflowschemeTool(cfg),
		tools_jql.CreateSanitisejqlqueriesTool(cfg),
		tools_user_search.CreateFinduserswithallpermissionsTool(cfg),
		tools_issues.CreateGeteditissuemetaTool(cfg),
		tools_workflows.CreateGetworkflowspaginatedTool(cfg),
		tools_issue_type_screen_schemes.CreateRemovemappingsfromissuetypescreenschemeTool(cfg),
		tools_jira_expressions.CreateAnalyseexpressionTool(cfg),
		tools_labels.CreateGetalllabelsTool(cfg),
		tools_permission_schemes.CreateGetpermissionschemegrantsTool(cfg),
		tools_permission_schemes.CreateCreatepermissiongrantTool(cfg),
		tools_tasks.CreateCanceltaskTool(cfg),
		tools_workflow_scheme_drafts.CreateGetworkflowschemedraftissuetypeTool(cfg),
		tools_workflow_scheme_drafts.CreateSetworkflowschemedraftissuetypeTool(cfg),
		tools_workflow_scheme_drafts.CreateDeleteworkflowschemedraftissuetypeTool(cfg),
		tools_project_avatars.CreateDeleteprojectavatarTool(cfg),
		tools_jira_settings.CreateSetapplicationpropertyTool(cfg),
		tools_issue_resolutions.CreateSearchresolutionsTool(cfg),
		tools_project_versions.CreateMergeversionsTool(cfg),
		tools_issue_types.CreateGetissuealltypesTool(cfg),
		tools_issue_types.CreateCreateissuetypeTool(cfg),
		tools_issue_properties.CreateBulkdeleteissuepropertyTool(cfg),
		tools_issue_properties.CreateBulksetissuepropertyTool(cfg),
		tools_screen_tabs.CreateGetallscreentabsTool(cfg),
		tools_screen_tabs.CreateAddscreentabTool(cfg),
		tools_screens.CreateAddfieldtodefaultscreenTool(cfg),
		tools_issue_fields.CreateUpdatecustomfieldTool(cfg),
		tools_workflow_scheme_project_associations.CreateGetworkflowschemeprojectassociationsTool(cfg),
		tools_workflow_scheme_project_associations.CreateAssignschemetoprojectTool(cfg),
		tools_server_info.CreateGetserverinfoTool(cfg),
		tools_issue_custom_field_contexts.CreateDeletecustomfieldcontextTool(cfg),
		tools_issue_custom_field_contexts.CreateUpdatecustomfieldcontextTool(cfg),
		tools_issue_link_types.CreateDeleteissuelinktypeTool(cfg),
		tools_issue_link_types.CreateGetissuelinktypeTool(cfg),
		tools_issue_link_types.CreateUpdateissuelinktypeTool(cfg),
		tools_screen_tabs.CreateMovescreentabTool(cfg),
		tools_license_metrics.CreateGetapproximatelicensecountTool(cfg),
		tools_project_email.CreateUpdateprojectemailTool(cfg),
		tools_project_email.CreateGetprojectemailTool(cfg),
		tools_issue_link_types.CreateGetissuelinktypesTool(cfg),
		tools_issue_link_types.CreateCreateissuelinktypeTool(cfg),
		tools_filters.CreateDeletefilterTool(cfg),
		tools_filters.CreateGetfilterTool(cfg),
		tools_filters.CreateUpdatefilterTool(cfg),
		tools_issue_custom_field_values_apps.CreateUpdatemultiplecustomfieldvaluesTool(cfg),
		tools_issues.CreateNotifyTool(cfg),
		tools_workflow_scheme_drafts.CreateCreateworkflowschemedraftfromparentTool(cfg),
		tools_filters.CreateCreatefilterTool(cfg),
		tools_issue_notification_schemes.CreateGetnotificationschemesTool(cfg),
		tools_issue_notification_schemes.CreateCreatenotificationschemeTool(cfg),
		tools_tasks.CreateGettaskTool(cfg),
		tools_user_search.CreateFinduserkeysbyqueryTool(cfg),
		tools_filter_sharing.CreateGetdefaultsharescopeTool(cfg),
		tools_filter_sharing.CreateSetdefaultsharescopeTool(cfg),
		tools_avatars.CreateGetallsystemavatarsTool(cfg),
		tools_project_categories.CreateRemoveprojectcategoryTool(cfg),
		tools_project_categories.CreateGetprojectcategorybyidTool(cfg),
		tools_project_categories.CreateUpdateprojectcategoryTool(cfg),
		tools_issue_fields.CreateRestorecustomfieldTool(cfg),
		tools_issue_notification_schemes.CreateRemovenotificationfromnotificationschemeTool(cfg),
		tools_issue_custom_field_contexts.CreateGetdefaultvaluesTool(cfg),
		tools_issue_custom_field_contexts.CreateSetdefaultvaluesTool(cfg),
		tools_dashboards.CreateDeletedashboarditempropertyTool(cfg),
		tools_dashboards.CreateGetdashboarditempropertyTool(cfg),
		tools_dashboards.CreateSetdashboarditempropertyTool(cfg),
		tools_status.CreateSearchTool(cfg),
		tools_screens.CreateGetscreensforfieldTool(cfg),
		tools_issue_type_schemes.CreateRemoveissuetypefromissuetypeschemeTool(cfg),
		tools_projects.CreateGetprojectTool(cfg),
		tools_projects.CreateUpdateprojectTool(cfg),
		tools_projects.CreateDeleteprojectTool(cfg),
		tools_issue_resolutions.CreateSetdefaultresolutionTool(cfg),
		tools_issues.CreateDeleteissueTool(cfg),
		tools_issues.CreateGetissueTool(cfg),
		tools_issues.CreateEditissueTool(cfg),
		tools_issues.CreateGetchangelogsbyidsTool(cfg),
		tools_app_migration.CreateMigrationresource_updateentitypropertiesvalue_putTool(cfg),
		tools_issue_security_schemes.CreateGetissuesecurityschemeTool(cfg),
		tools_issue_security_schemes.CreateUpdateissuesecurityschemeTool(cfg),
		tools_projects.CreateGetallstatusesTool(cfg),
		tools_users.CreateGetallusersTool(cfg),
		tools_issue_attachments.CreateGetattachmentmetaTool(cfg),
		tools_issue_worklogs.CreateGetworklogsforidsTool(cfg),
		tools_group_and_user_picker.CreateFindusersandgroupsTool(cfg),
		tools_filters.CreateGetmyfiltersTool(cfg),
		tools_issue_security_schemes.CreateSearchprojectsusingsecurityschemesTool(cfg),
		tools_issue_custom_field_values_apps.CreateUpdatecustomfieldvalueTool(cfg),
		tools_ui_modifications_apps.CreateDeleteuimodificationTool(cfg),
		tools_ui_modifications_apps.CreateUpdateuimodificationTool(cfg),
		tools_issue_custom_field_contexts.CreateGetissuetypemappingsforcontextsTool(cfg),
		tools_user_properties.CreateDeleteuserpropertyTool(cfg),
		tools_user_properties.CreateGetuserpropertyTool(cfg),
		tools_user_properties.CreateSetuserpropertyTool(cfg),
		tools_issue_comment_properties.CreateGetcommentpropertykeysTool(cfg),
		tools_groups.CreateGetusersfromgroupTool(cfg),
		tools_webhooks.CreateRefreshwebhooksTool(cfg),
		tools_issue_security_schemes.CreateSetdefaultlevelsTool(cfg),
		tools_issue_remote_links.CreateDeleteremoteissuelinkbyidTool(cfg),
		tools_issue_remote_links.CreateGetremoteissuelinkbyidTool(cfg),
		tools_issue_remote_links.CreateUpdateremoteissuelinkTool(cfg),
		tools_jql.CreateParsejqlqueriesTool(cfg),
		tools_issue_custom_field_contexts.CreateGetcustomfieldcontextsforprojectsandissuetypesTool(cfg),
		tools_issue_watchers.CreateGetiswatchingissuebulkTool(cfg),
		tools_license_metrics.CreateGetapproximateapplicationlicensecountTool(cfg),
		tools_issue_worklog_properties.CreateGetworklogpropertykeysTool(cfg),
		tools_project_versions.CreateCreateversionTool(cfg),
		tools_user_search.CreateFindusersTool(cfg),
		tools_dashboards.CreateGetdashboardspaginatedTool(cfg),
		tools_issue_field_configurations.CreateGetfieldconfigurationschememappingsTool(cfg),
		tools_issue_type_schemes.CreateReorderissuetypesinissuetypeschemeTool(cfg),
		tools_audit_records.CreateGetauditrecordsTool(cfg),
		tools_user_search.CreateFinduserswithbrowsepermissionTool(cfg),
		tools_issue_priorities.CreateMoveprioritiesTool(cfg),
		tools_workflow_transition_properties.CreateDeleteworkflowtransitionpropertyTool(cfg),
		tools_workflow_transition_properties.CreateGetworkflowtransitionpropertiesTool(cfg),
		tools_workflow_transition_properties.CreateCreateworkflowtransitionpropertyTool(cfg),
		tools_workflow_transition_properties.CreateUpdateworkflowtransitionpropertyTool(cfg),
		tools_issue_resolutions.CreateGetresolutionsTool(cfg),
		tools_issue_resolutions.CreateCreateresolutionTool(cfg),
		tools_filter_sharing.CreateDeletesharepermissionTool(cfg),
		tools_filter_sharing.CreateGetsharepermissionTool(cfg),
		tools_users.CreateGetuserTool(cfg),
		tools_users.CreateCreateuserTool(cfg),
		tools_users.CreateRemoveuserTool(cfg),
		tools_issue_field_configurations.CreateUpdatefieldconfigurationschemeTool(cfg),
		tools_issue_field_configurations.CreateDeletefieldconfigurationschemeTool(cfg),
		tools_issue_votes.CreateRemovevoteTool(cfg),
		tools_issue_votes.CreateGetvotesTool(cfg),
		tools_issue_votes.CreateAddvoteTool(cfg),
		tools_issue_type_screen_schemes.CreateAppendmappingsforissuetypescreenschemeTool(cfg),
		tools_project_versions.CreateGetversionrelatedissuesTool(cfg),
		tools_issue_comments.CreateGetcommentsTool(cfg),
		tools_issue_comments.CreateAddcommentTool(cfg),
		tools_issue_properties.CreateGetissuepropertykeysTool(cfg),
		tools_screen_schemes.CreateGetscreenschemesTool(cfg),
		tools_screen_schemes.CreateCreatescreenschemeTool(cfg),
		tools_filter_sharing.CreateGetsharepermissionsTool(cfg),
		tools_filter_sharing.CreateAddsharepermissionTool(cfg),
		tools_project_role_actors.CreateAddactorusersTool(cfg),
		tools_project_role_actors.CreateSetactorsTool(cfg),
		tools_project_role_actors.CreateDeleteactorTool(cfg),
		tools_project_roles.CreateGetprojectroleTool(cfg),
		tools_projects.CreateArchiveprojectTool(cfg),
		tools_issue_field_configurations.CreateGetallfieldconfigurationsTool(cfg),
		tools_issue_field_configurations.CreateCreatefieldconfigurationTool(cfg),
		tools_issues.CreateGeteventsTool(cfg),
		tools_project_components.CreateCreatecomponentTool(cfg),
		tools_workflow_schemes.CreateDeleteworkflowmappingTool(cfg),
		tools_workflow_schemes.CreateGetworkflowTool(cfg),
		tools_workflow_schemes.CreateUpdateworkflowmappingTool(cfg),
		tools_screens.CreateDeletescreenTool(cfg),
		tools_screens.CreateUpdatescreenTool(cfg),
		tools_screen_tab_fields.CreateRemovescreentabfieldTool(cfg),
		tools_project_permission_schemes.CreateGetsecuritylevelsforprojectTool(cfg),
		tools_webhooks.CreateGetfailedwebhooksTool(cfg),
		tools_issue_priorities.CreateDeletepriorityTool(cfg),
		tools_issue_priorities.CreateGetpriorityTool(cfg),
		tools_issue_priorities.CreateUpdatepriorityTool(cfg),
		tools_dashboards.CreateRemovegadgetTool(cfg),
		tools_dashboards.CreateUpdategadgetTool(cfg),
		tools_issues.CreateCreateissuesTool(cfg),
		tools_app_properties.CreateAddonpropertiesresource_getaddonproperties_getTool(cfg),
		tools_groups.CreateCreategroupTool(cfg),
		tools_groups.CreateRemovegroupTool(cfg),
		tools_groups.CreateGetgroupTool(cfg),
		tools_issue_types.CreateDeleteissuetypeTool(cfg),
		tools_issue_types.CreateGetissuetypeTool(cfg),
		tools_issue_types.CreateUpdateissuetypeTool(cfg),
		tools_application_roles.CreateGetallapplicationrolesTool(cfg),
		tools_workflow_schemes.CreateDeletedefaultworkflowTool(cfg),
		tools_workflow_schemes.CreateGetdefaultworkflowTool(cfg),
		tools_workflow_schemes.CreateUpdatedefaultworkflowTool(cfg),
		tools_project_versions.CreateGetversionunresolvedissuesTool(cfg),
		tools_users.CreateBulkgetusersmigrationTool(cfg),
		tools_project_types.CreateGetaccessibleprojecttypebykeyTool(cfg),
		tools_groups.CreateBulkgetgroupsTool(cfg),
		tools_issue_properties.CreateGetissuepropertyTool(cfg),
		tools_issue_properties.CreateSetissuepropertyTool(cfg),
		tools_issue_properties.CreateDeleteissuepropertyTool(cfg),
		tools_users.CreateGetusergroupsTool(cfg),
		tools_issue_fields.CreateGettrashedfieldspaginatedTool(cfg),
		tools_permissions.CreateGetbulkpermissionsTool(cfg),
		tools_issue_worklog_properties.CreateDeleteworklogpropertyTool(cfg),
		tools_issue_worklog_properties.CreateGetworklogpropertyTool(cfg),
		tools_issue_worklog_properties.CreateSetworklogpropertyTool(cfg),
		tools_avatars.CreateGetavatarimagebytypeTool(cfg),
		tools_users.CreateBulkgetusersTool(cfg),
		tools_issue_comments.CreateDeletecommentTool(cfg),
		tools_issue_comments.CreateGetcommentTool(cfg),
		tools_issue_comments.CreateUpdatecommentTool(cfg),
		tools_jira_settings.CreateGetconfigurationTool(cfg),
		tools_project_key_and_name_validation.CreateValidateprojectkeyTool(cfg),
		tools_issues.CreateCreateissueTool(cfg),
		tools_user_search.CreateFindbulkassignableusersTool(cfg),
		tools_screen_schemes.CreateUpdatescreenschemeTool(cfg),
		tools_screen_schemes.CreateDeletescreenschemeTool(cfg),
		tools_issue_custom_field_contexts.CreateGetcontextsforfieldTool(cfg),
		tools_issue_custom_field_contexts.CreateCreatecustomfieldcontextTool(cfg),
		tools_instance_information.CreateGetlicenseTool(cfg),
		tools_groups.CreateRemoveuserfromgroupTool(cfg),
		tools_groups.CreateAddusertogroupTool(cfg),
		tools_project_versions.CreateDeleteandreplaceversionTool(cfg),
		tools_project_avatars.CreateCreateprojectavatarTool(cfg),
		tools_dashboards.CreateGetallavailabledashboardgadgetsTool(cfg),
	}
}
